# Generated by Django 5.2.4 on 2025-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='defaults/cover.jpg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='defaults/profile.jpg', upload_to='profile_images/'),
        ),
    ]
