# Generated by Django 5.2.5 on 2025-08-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='defaults/cover.jpg', null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='defaults/profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
