# Generated by Django 5.2.5 on 2025-08-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_creatred_post_created_alter_notification_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='respost',
        ),
    ]
